# Generated by Django 5.1 on 2024-09-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0007_carts_cartitem_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
