# Generated by Django 5.1 on 2024-09-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0010_alter_cart_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
