# Generated by Django 5.1 on 2024-09-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0017_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
